// Operation identifiers consumed by src/lib/mock-client.ts's useQuery shim.
// Named to match the original GraphQL operations they replace.

export const GET_STATS = 'GET_STATS';
export const GET_RECENT_BLOCKS = 'GET_RECENT_BLOCKS';
export const GET_RECENT_TRANSACTIONS = 'GET_RECENT_TRANSACTIONS';
export const GET_BLOCK_BY_NUMBER = 'GET_BLOCK_BY_NUMBER';
export const GET_BLOCKS = 'GET_BLOCKS';
export const GET_TRANSACTION_BY_HASH = 'GET_TRANSACTION_BY_HASH';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTION_COUNTS_BY_STATUS = 'GET_TRANSACTION_COUNTS_BY_STATUS';
export const GET_TRANSACTION_COUNTS_BY_DIRECTION = 'GET_TRANSACTION_COUNTS_BY_DIRECTION';
export const GET_TOP_ADDRESSES = 'GET_TOP_ADDRESSES';
export const GET_ADDRESS_STATS = 'GET_ADDRESS_STATS';
export const GET_ADDRESS_PROFILE = 'GET_ADDRESS_PROFILE';
export const GET_ADDRESS_TRANSACTIONS = 'GET_ADDRESS_TRANSACTIONS';
export const GET_ADDRESS_GROWTH_CHART = 'GET_ADDRESS_GROWTH_CHART';
